{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "location-master-service.fullname" . }}
  labels:
    {{- include "location-master-service.labels" . | nindent 4 }}
spec:
  parentRefs:
  {{- range .Values.gateway.parentRefs }}
  - name: {{ .name }}
    {{- if .namespace }}
    namespace: {{ .namespace }}
    {{- end }}
    {{- if .sectionName }}
    sectionName: {{ .sectionName }}
    {{- end }}
  {{- end }}
  {{- if .Values.gateway.hostnames }}
  hostnames:
  {{- range .Values.gateway.hostnames }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api/v1/locations
    - path:
        type: PathPrefix
        value: /actuator
    backendRefs:
    - name: {{ include "location-master-service.fullname" . }}
      port: {{ .Values.service.port }}
      weight: 100
  - matches:
    - path:
        type: PathPrefix
        value: /swagger-ui
    - path:
        type: PathPrefix
        value: /api-docs
    backendRefs:
    - name: {{ include "location-master-service.fullname" . }}
      port: {{ .Values.service.port }}
      weight: 100
{{- end }}
